# Generated by Django 3.2.6 on 2021-08-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210822_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-is_main']},
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='main_tag',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Article'),
        ),
    ]
